### ISSUE TITLE
TypeError: Error instantiating 'hulc.utils.transforms.NormalizeVector' : new(): data must be a sequence (got float)

### ISSUE THREAD

**Issue by Shua-Kang** [ezhang7423/hulc-baseline#5]
Hi, I think there is a bug in utils/transform.py. Here is the torch.Tensor(1.0):
https://github.com/ezhang7423/hulc-baseline/blob/86f0efbdddd909720e45673dba9262ceafdf6308/hulc/utils/transforms.py#L24-L25
But torch.Tensor() is for the multi-dimensional matrix so it will show this error:
```bash
Traceback (most recent call last):
  File "/home/shua/mambaforge/envs/lcd/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/home/shua/language-control-diffusion/submodules/hulc-baseline/hulc/utils/transforms.py", line 27, in __init__
    self.std = torch.Tensor(std)
TypeError: new(): data must be a sequence (got float)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shua/language-control-diffusion/src/lcd/scripts/diffuser.py", line 152, in <module>
    eval_model(
  File "/home/shua/language-control-diffusion/src/lcd/scripts/diffuser.py", line 145, in eval_model
    rollout.main(seed=args.seed, num_sequences=num_evals)
  File "/home/shua/language-control-diffusion/src/lcd/apps/rollout.py", line 49, in main
    ) = get_default_model_and_env(
  File "/home/shua/language-control-diffusion/submodules/hulc-baseline/hulc/evaluation/utils.py", line 33, in get_default_model_and_env
    data_module.setup()
  File "/home/shua/language-control-diffusion/submodules/hulc-baseline/hulc/datasets/hulc_data_module.py", line 84, in setup
    self.train_transforms = {
  File "/home/shua/language-control-diffusion/submodules/hulc-baseline/hulc/datasets/hulc_data_module.py", line 85, in <dictcomp>
    cam: [hydra.utils.instantiate(transform) for transform in transforms.train[cam]] for cam in transforms.train
  File "/home/shua/language-control-diffusion/submodules/hulc-baseline/hulc/datasets/hulc_data_module.py", line 85, in <listcomp>
    cam: [hydra.utils.instantiate(transform) for transform in transforms.train[cam]] for cam in transforms.train
  File "/home/shua/mambaforge/envs/lcd/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/home/shua/mambaforge/envs/lcd/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "/home/shua/mambaforge/envs/lcd/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 64, in _call_target
    raise type(e)(
  File "/home/shua/mambaforge/envs/lcd/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/home/shua/language-control-diffusion/submodules/hulc-baseline/hulc/utils/transforms.py", line 27, in __init__
    self.std = torch.Tensor(std)
TypeError: Error instantiating 'hulc.utils.transforms.NormalizeVector' : new(): data must be a sequence (got float)
``` 
lib version:
pytorch3d==0.7.2
torch==1.12.1
torchvision==0.13.0

I wonder how to solve it then I can reproduce the results. Thank you very much!

**Comment by ezhang7423** [comment]
Yes, this is certainly a bug! I also found the same bug when playing around with the original repository :). In the end, you can solve it by `self.std = torch.Tensor([std])`
